# Generated by Django 4.1.1 on 2022-09-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtelplans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyplan',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
